// The C++ arm IK must give exactly the same answer as the original Python
// MasterPi/ArmIK for every case in data/arm_ik_reference.txt (generated by
// running ArmIK.setPitchRangeMoving on a grid of 3564 targets).
#include <gtest/gtest.h>

#include <fstream>
#include <sstream>
#include <string>

#include "robot_board/arm.hpp"

#ifndef ARM_IK_REFERENCE
#error "ARM_IK_REFERENCE must point to test/data/arm_ik_reference.txt"
#endif

TEST(ArmIK, MatchesOriginalPythonOnEveryReferenceCase) {
  std::ifstream in(ARM_IK_REFERENCE);
  ASSERT_TRUE(in) << "missing " << ARM_IK_REFERENCE;
  robot_board::ArmIK ik;
  std::string line;
  int cases = 0, reachable = 0;
  while (std::getline(in, line)) {
    if (line.empty() || line[0] == '#') {continue;}
    std::istringstream is(line);
    double x, y, z, alpha, a1, a2;
    std::string first;
    is >> x >> y >> z >> alpha >> a1 >> a2 >> first;
    const auto got = ik.solve(x, y, z, alpha, a1, a2);
    ++cases;
    if (first == "NONE") {
      EXPECT_FALSE(got.has_value()) << line;
      continue;
    }
    ++reachable;
    int s3 = std::stoi(first), s4, s5, s6;
    double used;
    is >> s4 >> s5 >> s6 >> used;
    ASSERT_TRUE(got.has_value()) << line;
    EXPECT_EQ(got->servo3, s3) << line;
    EXPECT_EQ(got->servo4, s4) << line;
    EXPECT_EQ(got->servo5, s5) << line;
    EXPECT_EQ(got->servo6, s6) << line;
    EXPECT_DOUBLE_EQ(got->alpha, used) << line;
  }
  EXPECT_EQ(cases, 3564);
  EXPECT_GT(reachable, 1000);
}

TEST(ArmIK, UnreachableIsNotAGuess) {
  robot_board::ArmIK ik;
  EXPECT_FALSE(ik.solve(0, 40, 10, 0, -90, 90).has_value());   // beyond 22.2 cm reach
}

TEST(ArmPoses, KnownPoses) {
  const auto & p = robot_board::arm_poses();
  ASSERT_TRUE(p.count("stand"));
  EXPECT_EQ(p.at("stand").s3, 695);
  EXPECT_EQ(p.at("stand").s4, 2415);
}
